### ISSUE TITLE
Broken data references

### ISSUE THREAD

**Issue by timconsidine** [BetaHuhn/ackee-report#89] opened 2021-07-10 06:24 UTC
**🐞 Describe the bug**

Used to be working
After V2 it changed
Report shows mangled data for pages and referrers, and broken average calculations

**🖼️ Screenshots**

See attached

**⚙️ Environment**
![Screenshot 2021-07-10 at 09 20 06](https://user-images.githubusercontent.com/28682881/125154015-889c8080-e160-11eb-9f3a-918d3a05ab80.png)

 - OS: Ubuntu
 - Version 20.04
 - Ackee version : 3.1.1

**Comment by BetaHuhn** [comment] 2021-07-10 15:59
Thanks for reporting this. Working on a fix asap.

**Comment by BetaHuhn** [comment] 2021-07-10 16:51
Fixed in [v2.0.1](https://github.com/BetaHuhn/ackee-report/releases/tag/v2.0.1).

This was caused by the recent changes to Ackee's API with v3.1.0.

**Closed by BetaHuhn** 2021-07-10 16:51 UTC
Labels: bug
